version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: band-sheets-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - band-sheets-network-dev
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: ./band-sheets-backend
      dockerfile: Dockerfile
    container_name: band-sheets-backend-dev
    ports:
      - "5050:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/bandsheets
      - JWT_SECRET=band_sheets_jwt_secret_for_dev_only
      - JWT_EXPIRES_IN=30d
      - JWT_COOKIE_EXPIRES_IN=30
    depends_on:
      - mongodb
    networks:
      - band-sheets-network-dev
    restart: unless-stopped
    volumes:
      - ./band-sheets-backend:/app
      - /app/node_modules

  # Frontend service
  frontend:
    build:
      context: ./band-sheet-creator
      dockerfile: Dockerfile
    container_name: band-sheets-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5050/api
    depends_on:
      - backend
    networks:
      - band-sheets-network-dev
    restart: unless-stopped
    volumes:
      - ./band-sheet-creator:/app
      - /app/node_modules

networks:
  band-sheets-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev: